# Generated by Django 2.0.1 on 2018-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jpider_memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('extfield1', models.CharField(max_length=300)),
                ('extfield2', models.CharField(max_length=300)),
                ('extfield3', models.CharField(max_length=300)),
                ('extfield4', models.CharField(max_length=300)),
                ('extfield5', models.CharField(max_length=300)),
                ('extfield6', models.CharField(max_length=300)),
                ('extfield7', models.CharField(max_length=300)),
                ('extfield8', models.CharField(max_length=300)),
                ('extfield9', models.CharField(max_length=300)),
                ('extfield10', models.CharField(max_length=300)),
            ],
        ),
    ]
